=== valtimo-platform/valtimo-backend-libraries/case/src/main/resources/config/case/schema/case-list.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://json-schema.org/draft-07/schema#",
    "title": "Form flow definition",
    "description": "Representation of a form flow definition",
    "type": "array",
    "additionalProperties": false,
    "items": {
        "type": "object",
        "properties": {
            "title": {
                "type": "string"
            },
            "key": {
                "type": "string"
            },
            "path": {
                "type": "string"
            },
            "displayType": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string"
                    },
                    "displayTypeParameters": {
                        "type": "object"
                    }
                },
                "required": [
                    "type"
                ]
            },
            "sortable": {
                "type": "boolean"
            },
            "defaultSort": {
                "type": "string"
            },
            "order": {
                "type": "integer"
            }
        },
        "required": [
            "key",
            "path",
            "displayType",
            "sortable"
        ]
    }
}

=== valtimo-platform/valtimo-backend-libraries/case/src/test/resources/config/case/list/house.json
[
    {
        "key": "test",
        "title": "some-title",
        "path": "test:createdOn",
        "displayType": {
            "type": "date",
            "displayTypeParameters": {
                "dateFormat": "yyyy-MM-dd"
            }
        },
        "sortable": false,
        "defaultSort": "DESC",
        "order": 0
    },
    {
        "key": "modifiedOn",
        "path": "test:modifiedOn",
        "displayType": {
            "type": "date",
            "displayTypeParameters": {
                "dateFormat": null
            }
        },
        "sortable": true
    }
]
